; =====================================================================
; COMMON CONFIGURATION (Applies to both receiver and transmitter)
; =====================================================================
[env]
platform = atmelavr
board_build.framework = custom

; common onfiguration for mySmartUSB light ()
; Hier stand vorhin noch der "custom"-Kram. Jetzt sauber auf AVR911/109:
;upload_protocol = avr109
;upload_speed = 57600
;upload_flags = -u

upload_protocol = custom

; =====================================================================
; ENVIRONMENT 1: Receiver (ATmega8)
; =====================================================================
[env:receiver]
board = ATmega8
board_build.f_cpu = 8000000L  ; internal RC oscillator at 8 MHz (fuse settings: 0xE4)
build_src_filter = +<shared/> +<receiver/>
build_flags = 
    -Os
    -I src/shared
    -D SPI_MODE          ; Activates Hardware SPI in rf12.c
    -D RF12_INTERRUPT    ; Activates Interrupts and Variables in rf12.c and rf12.h

; Override the default upload command to use my custom AVR programmer tool
; Wir nutzen den integrierten AVRDUDE-Standard von PlatformIO
upload_protocol = custom
upload_port = COM3

; Das stk500v2-Protokoll ist der native Modus des mySmartUSB light
upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    atmega8
    -P
    $UPLOAD_PORT
    -c
    stk500v2
    -F  ; Ignoriert den efuse-Fehler des ATmega8
    -u  ; Deaktiviert den Safemode-Rücklese-Check

upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i


; =====================================================================
; ENVIRONMENT 2: Transmitter (ATtiny2313A)
; =====================================================================
[env:transmitter]
platform = atmelavr
board = attiny2313
board_build.framework = custom
; The ATtiny2313A has an internal RC oscillator at 8 MHz, but we want to run it at 4 MHz for lower power consumption 
; and 3.3V operation. Therefore, we set the f_cpu to 4 MHz and configure the fuses accordingly.
board_build.f_cpu = 4000000L  ; internal RC oscillator at 4 MHz; Start-up time: 14 CK + 4.1 ms
                              ; lower energy consumption; stability (low fuse settings: 0xD2, high fuse settings: 0xDF)
build_src_filter = +<shared/> +<transmitter/>
build_flags = 
    -Os
    -I src/shared
    -D USI_MODE   ; Activates USI SPI in rf12.c (instead of Hardware SPI, which the ATtiny2313 doesn't have)
    -D RF12_INTERRUPT ; Activates Interrupts and Variables in rf12.c and rf12.h

upload_protocol = custom
upload_port = COM3

upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    t2313
    -P
    ${env:transmitter.upload_port}  ; Setzt explizit das COM3 von oben ein
    -c
    stk500v2

upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i